language: python
env:
  - UPDATED_FAIL2BAN=true
  - UPDATED_FAIL2BAN=false
install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - if [ "$UPDATED_FAIL2BAN" = "true" ]; then sudo add-apt-repository -y ppa:leonbo/fail2ban ; fi
  - sudo apt-get update
  - sudo apt-get install -y nginx
  - sudo apt-get install -y fail2ban
  - fail2ban-client --version
  - pip install ansible
#  - sudo service fail2ban restart
  - ls /etc/fail2ban/ -al
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - tests/test.sh
