language: python

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y nginx
  - sudo apt-get install -y fail2ban
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - tests/syntax_check.sh
