language: python

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo add-apt-repository -y ppa:jan-hoffmann/fail2ban
  - sudo apt-get update
  - sudo apt-get install -y nginx
  - sudo apt-get install -y fail2ban
  - fail2ban-client --version
  - pip install ansible
#  - sudo service fail2ban restart
  - ls /etc/fail2ban/ -al
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - tests/test.sh
